format_version: 3
pipelines:
  HelloApp:
    group: myFirstpipeline
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      - git:
          url: https://github.com/htetgit/Hello-World-Test.git
          branch: main
          shallow_clone: false
          auto_update: true
    stages:
      - name: Build
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        jobs:
          - name: Compile
            tasks:
              - exec:
                  command: go
                  arguments: ["version"]
                  working_directory: "C:\\Program Files (x86)\\Go Agent\\pipelines\\Hello-Test-App\\src\\hello-app"
              - exec:
                  command: go
                  arguments: ["env"]
                  working_directory: "C:\\Program Files (x86)\\Go Agent\\pipelines\\Hello-Test-App\\src\\hello-app"
              - exec:
                  command: go
                  arguments: ["mod", "tidy"]
                  working_directory: "C:\\Program Files (x86)\\Go Agent\\pipelines\\Hello-Test-App\\src\\hello-app"
              - exec:
                  command: go
                  arguments: ["build", "-o", "hello-world", "."]
                  working_directory: "C:\\Program Files (x86)\\Go Agent\\pipelines\\Hello-Test-App\\src\\hello-app"
      - name: Dockerize
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        jobs:
          - name: BuildDockerImage
            tasks:
              - exec:
                  command: docker
                  arguments: ["build", "-t", "my-golang-app", "."]
                  working_directory: "C:\\Program Files (x86)\\Go Agent\\pipelines\\Hello-Test-App\\src\\hello-app"
              - exec:
                  command: docker
                  arguments: ["run", "-d", "-p", "8080:8080", "my-golang-app"]
                  working_directory: "C:\\Program Files (x86)\\Go Agent\\pipelines\\Hello-Test-App\\src\\hello-app"
